// packages/react-app/src/components/Tabs.tsx
import React from 'react';

const tabs = [
  { label: 'ALL', count: 304, active: true },
  { label: 'Carton &Shipping Label Pending', count: 83 },
  { label: 'Unpaid', count: 8 },
  { label: 'Being Processed', count: 15 },
  { label: 'BOL Pending&Awaiting Pickup', count: 23 },
];

export default function Tabs() {
  return (
    <div className="flex gap-4 items-start w-full overflow-x-auto pb-2">
      {tabs.map((tab, index) => (
        <div
          key={index}
          className={`flex flex-col items-center justify-center px-4 py-[9px] h-9 rounded-[100px] shrink-0 whitespace-nowrap cursor-pointer transition-colors ${
            tab.active ? 'bg-[#f2f2f2]' : 'bg-[#f2f2f2] hover:bg-gray-200'
          }`}
        >
          <div className="text-sm text-[#333] leading-[18px] font-normal font-arial">
            <span>{tab.label}</span>
            <span className="font-bold">({tab.count})</span>
          </div>
        </div>
      ))}
    </div>
  );
}

// packages/vue-app/src/components/Tabs.vue
<script setup lang="ts">
const tabs = [
  { label: 'ALL', count: 304, active: true },
  { label: 'Carton &Shipping Label Pending', count: 83 },
  { label: 'Unpaid', count: 8 },
  { label: 'Being Processed', count: 15 },
  { label: 'BOL Pending&Awaiting Pickup', count: 23 },
]
</script>

<template>
  <div class="tabs-container">
    <div
      v-for="(tab, index) in tabs"
      :key="index"
      class="tab-item"
      :class="{ active: tab.active }"
    >
      <div class="tab-content">
        <span>{{ tab.label }}</span>
        <span class="count">({{ tab.count }})</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.tabs-container {
  display: flex;
  gap: 16px;
  align-items: flex-start;
  width: 100%;
  overflow-x: auto;
  padding-bottom: 8px;
}

.tab-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 9px 16px;
  height: 36px;
  border-radius: 100px;
  flex-shrink: 0;
  white-space: nowrap;
  cursor: pointer;
  background-color: #f2f2f2;
  transition: background-color 0.2s;
}

.tab-item:hover:not(.active) {
  background-color: #e0e0e0;
}

.tab-content {
  font-family: Arial, sans-serif;
  font-size: 14px;
  line-height: 18px;
  color: #333;
}

.count {
  font-weight: bold;
}
</style>
